language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - dev_4_4
    - dev_5_0
    - dev_5_1
    - dev_5_2
env:
  global:
    - secure: "FhQxNU0O4aylgoJDK6ymEjYc3ILFl4IjjrPx7OdCeG+UMqBc9da/0CM/l6ehWHHxn0VQUc0+7qZgQjguRdMRGVApMIxY2a9vipYnG6DwYKQD59oqoJHfTAqtb+50vdC85pyNiBIetraOdyfJfjVTmAgXRTUwW5GdgSklJFsqjIY="
    - secure: "PYwpkDwhGfQgIF9axubaKo6zuDxl+PF3zKc86SRxnGTk7bNYd5NFMBP1IAq4oBe0TgujC6fc4lH3Od6FpIy3PcFuRHpQaSwg8r5ZvyvNqGVlglyOitLKoLnByXDUkmATPKyMZDnVvPepGLs/6lsw9yjlO881Wy00JWYGHP2iWM8="

after_success: if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then mvn -U -B -e clean deploy -DskipTests; fi
