language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - dev_4_4
    - dev_5_0
    - dev_5_1
    - dev_5_2
    - dev_5_3
    - dev_5_4

after_success: if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then mvn -U -B -e clean deploy -DskipTests; fi
